import {area, difficulty} from './helpers'
import { Thickness,NeighboursSelectionMode, LevelAnnotationConfig, AnnotationType, Colors, LineType,ChildrenPlacementType,ItemShapeType, GroupByType, PageFitMode, Enabled } from 'basicprimitives';
import MateriaCard from '../Components/MateriaCard';


const materias = [
  {   
    id: 23,
    levelOffset: 0,
    parents: null,
    children: [16,14,10],
    hoursPerWeek: 4,
    totalHours: 64,
    title: "Materias Complementaria",
    description: "Materias Complementaria",
    itemTitleColor: area.MC.color, 
    studyGroup: area.MC.name,
    studyArea: area.MC.acronim,
    matrixId:'1',
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Sexto',
    templateName: "materiaTemplate"

  },
  {   
    id: 22,
    levelOffset: 1,
    parents: null,
    children: [],
    hoursPerWeek: 2,
    totalHours: 32,
    title: "Materia UNAHUR",
    description: "Materia UNAHUR",
    itemTitleColor: area.Gral.color,
    studyGroup: area.Gral.name,
    studyArea: area.Gral.acronim,
    matrixId:'1',
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Sexto',
    templateName: "materiaTemplate",

  },
  {   
    id: 21,
    parents: null,
    children: [20,18,19,14],
    levelOffset: 0,
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Práctica Profesional Supervisada",
    description: "Práctica Profesional Supervisada",
    itemTitleColor: area.PPS.color,
    studyGroup: area.PPS.name,
    studyArea: area.PPS.acronim,
    matrixId:'1',
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Sexto',
    templateName: "materiaTemplate",
  },
  {   
    id: 20,
    levelOffset: 3,
    parents: [21],
    children: [13,15,16,9],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Desarrollo de Aplicaciones",
    description: "Desarrollo de Aplicaciones",
    itemTitleColor: area.ISBDySI.color,
    studyGroup: area.ISBDySI.name,
    studyArea: area.ISBDySI.acronim,
    matrixId:'2',
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/Des-App/',
    cuatrimestre:'Quinto',
    templateName: "materiaTemplate",
  },
  {   
    id: 19,
    parents: [21],
    children: [11,12],
    hoursPerWeek: 4,
    totalHours: 64,
    title: "Laboratorio de Sistemas Operativos y Redes",
    description: "Laboratorio de Sistemas Operativos y Redes",
    itemTitleColor: area.ASOyR.color,
    studyGroup: area.ASOyR.name,
    studyArea:area.ASOyR.acronim,
    matrixId:'2',
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/Labo/',
    cuatrimestre:'Quinto',
    templateName: "materiaTemplate",
  },
  {   
    id: 18,
    parents: [21],
    children: [5],
    hoursPerWeek: 4,
    totalHours: 64,
    title: "Programación Funcional",
    description: "Programación Funcional",
    itemTitleColor: area.AyL.color,
    studyGroup:area.AyL.name,
    studyArea: area.AyL.acronim,
    matrixId:'2',
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/Funcional/',
    cuatrimestre:'Quinto',
    templateName: "materiaTemplate",
  },
  {   
    id: 17,
    parents: null,
    children: [8],
    hoursPerWeek: 2,
    totalHours: 32,
    title: "Ingles II",
    description: "Ingles II",
    itemTitleColor: area.Gral.color,
    studyGroup: area.Gral.name,
    studyArea: area.Gral.acronim,
    matrixId:'3',
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Cuarto',
    templateName: "materiaTemplate",
  },
  {   
    id: 16,
    parents: [20,23],
    children: [10],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Elementos de Ingeniería de Software",
    description: "Elementos de Ingeniería de Software",
    itemTitleColor: area.ISBDySI.color,
    studyGroup: area.ISBDySI.name,
    studyArea: area.ISBDySI.acronim,
    matrixId:'3',
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/Elementos/',
    cuatrimestre:'Cuarto',
    templateName: "materiaTemplate",
  },
  {   
    id: 15,
    parents: [20],
    children: [10,7],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Estrategias de Persistencia",
    description: "Estrategias de Persistencia",
    itemTitleColor: area.ISBDySI.color,
    studyGroup: area.ISBDySI.name,
    studyArea: area.ISBDySI.acronim,
    matrixId:'3',
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/Persistencia/',
    cuatrimestre:'Cuarto',
    templateName: "materiaTemplate",
  },
  {   
    id: 14,
    parents: [21,23],
    children: [5],
    hoursPerWeek: 4,
    totalHours: 64,
    title: "Programación Concurrente",
    description: "Programación Concurrente",
    itemTitleColor: area.AyL.color,
    studyGroup: area.AyL.name,
    studyArea: area.AyL.acronim,
    matrixId:'3',
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Cuarto',
    templateName: "materiaTemplate",
  },
  {   
    id: 13,
    parents: [20],
    children: [10],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Construcción de Interfaces de Usuario",
    description: "Construcción de Interfaces de Usuario",
    itemTitleColor: area.ISBDySI.color,
    studyGroup: area.ISBDySI.name,
    studyArea: area.ISBDySI.acronim,
    matrixId:'3',
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/Interfaces/',
    cuatrimestre:'Cuarto',
    templateName: "materiaTemplate",
  },
  {   
    id: 12,
    parents: [19],
    children: [2,3],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Sistemas Operativos",
    description: "Sistemas Operativos",
    itemTitleColor: area.ASOyR.color,
    studyGroup: area.ASOyR.name,
    studyArea: area.ASOyR.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/sis-op/',
    cuatrimestre:'Tercer',
    templateName: "materiaTemplate",
  },
  {   
    id: 11,
    parents: [19],
    children: [3],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Redes de Computadoras",
    description: "Redes de Computadoras",
    itemTitleColor: area.ASOyR.color,
    studyGroup: area.ASOyR.name,
    studyArea: area.ASOyR.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/redes/',
    cuatrimestre:'Tercer',
    templateName: "materiaTemplate",
  },
  {   
    id: 10,
    parents: [13,15,16,23],
    children: [6],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Programación con Objetos II",
    description: "Programación con Objetos II",
    itemTitleColor: area.AyL.color,
    studyGroup: area.AyL.name,
    studyArea: area.AyL.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/objetos-2/',
    cuatrimestre:'Tercer',
    templateName: "materiaTemplate",
  },
  {   
    id: 9,
    parents: [20],
    children: [1],
    hoursPerWeek: 4,
    totalHours: 64,
    title: "Matemática II",
    description: "Matemática II",
    itemTitleColor: area.CB.color,
    studyGroup: area.CB.name,
    studyArea: area.CB.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/matematica-2/',
    cuatrimestre:'Tercer',
    templateName: "materiaTemplate",
  },
  {   
    id: 8,
    parents: [17],
    children:[],
    hoursPerWeek: 2,
    totalHours: 32,
    title: "Inglés I",
    description: "Inglés I",
    itemTitleColor: area.Gral.color,
    studyGroup: area.Gral.name,
    studyArea: area.Gral.acronim,
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Segundo',
    templateName: "materiaTemplate",
  },
  {   
    id: 7,
    parents: [15],
    children:[1],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Bases de Datos ",
    description: "Bases de Datos ",
    itemTitleColor: area.ISBDySI.color,
    studyGroup: area.ISBDySI.name,
    studyArea: area.ISBDySI.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/bases-datos/',
    cuatrimestre:'Segundo',
    templateName: "materiaTemplate",
  },
  {   
    id: 6,
    parents: [10],
    children:[2],
    hoursPerWeek: 8,
    totalHours: 128,
    title: "Programación con Objetos I",
    description: "Programación con Objetos I",
    itemTitleColor: area.AyL.color,
    studyGroup: area.AyL.name,
    studyArea: area.AyL.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/objetos-1/',
    cuatrimestre:'Segundo',
    templateName: "materiaTemplate",
  },
  {   
    id: 5,
    parents: [14,18],
    children:[2],
    hoursPerWeek: 8,
    totalHours: 128,
    title: "Estructuras de Datos",
    description: "Estructuras de Datos",
    itemTitleColor: area.TC.color,
    studyGroup: area.TC.name,
    studyArea: area.TC.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/est-datos/',
    cuatrimestre:'Segundo',
    templateName: "materiaTemplate",
  },
  {   
    id: 4,
    parents: null,
    children:[],
    hoursPerWeek: 2,
    totalHours: 32,
    title: "Nuevos Entornos y Lenguajes",
    description: "Nuevos Entornos y Lenguajes",
    itemTitleColor: area.Gral.color,
    studyGroup: area.Gral.name,
    studyArea: area.Gral.acronim,
    image: difficulty.easy,
    url:null,
    cuatrimestre:'Primer',
    templateName: "materiaTemplate",
  },
  {   
    id: 3,
    parents: [11,12],
    children:[],
    hoursPerWeek: 6,
    totalHours: 96,
    title: "Organización de Computadoras",
    description: "Organización de Computadoras",
    itemTitleColor: area.ASOyR.color,
    studyGroup: area.ASOyR.name,
    studyArea: area.ASOyR.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/org-comp/',
    cuatrimestre:'Primer',
    templateName: "materiaTemplate",
  },
  {   
    id: 2,
    parents: [5,6,12],
    children:[],
    hoursPerWeek: 8,
    totalHours: 128,
    title: "Introducción a la Programación",
    description: "Introducción a la Programación",
    itemTitleColor: area.AyL.color,
    studyGroup: area.AyL.name,
    studyArea: area.AyL.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/introduccion-programacion/',
    cuatrimestre:'Primer',
    templateName: "materiaTemplate",
  },
  {   
    id: 1,
    parents: [7,9],
    children:[],
    hoursPerWeek: 8,
    totalHours: 128,
    title: "Matemática I",
    description: "Matemática I",
    itemTitleColor: area.CB.color,
    studyGroup: area.CB.name,
    studyArea: area.CB.acronim,
    image: difficulty.easy,
    url:'https://informaticaunahur.github.io/matematica-1/',
    cuatrimestre:'Primer',
    templateName: "materiaTemplate",
  },
]

export const config = {
    items: materias,
    
    annotations: [{
      annotationType: AnnotationType.Connector,
    }
    ],
    showExtraArrows:false,
    linesWidth: 2,
    arrowsDirection: GroupByType.Parents,
    pageFitMode: PageFitMode.None,
    linesColor: '#000000',
    hasSelectorCheckbox: Enabled.False,
    scale: 0.8, // de aca se puede hacer "zoom"
    normalLevelShift: 40,
    normalItemsInterval: 30,
    




    templates: [{
      name: "materiaTemplate",
      itemSize: { width: 170, height: 200 },
      onItemRender: ({ context: itemConfigu }) => 
          <MateriaCard itemConfig={itemConfigu}/>
      
  }]

  };


